### ISSUE TITLE
E100 simulaton not working

### ISSUE THREAD

**Issue by DongMuJi** [gaitech-robotics/RIA-E100#1]
Hi 
I just follow the manual,  download the lasted e100_sim package from the github ,catkin make no error and roslaunch the E100 simulation
`roslaunch e100_sim gazebo.launch`
It will open the rviz, but I can not see the robot model in the world. No error show. Is there something I missing?

**Comment by gaitech-robotics** [comment]
@DongMuJi can you see the model in gazebo? it would be easy to understand if you post picture of gazebo and rviz after you launched.

**Comment by DongMuJi** [comment]
> @DongMuJi can you see the model in gazebo? it would be easy to understand if you post picture of gazebo and rviz after you launched.

Sorry I make a mistake. Thank you for your help! I will close this issue.
